# MiniCPS .travis.yml
#
# Commits that have [ci skip] anywhere in the commit messages are ignored by Travis CI.

# NOTE: Travis will use a non docker based infrastructure
# NOTE: because of pymodbus
sudo: required

language: python

branches:
  only:
    - master

python:
  - "2.6"
  - "2.7"

# NOTE: Travis-ci automatically preinstalls
# pytest
# nose
# mock

# NOTE: Travis-ci automatically runs
#
# pip install -r requirements.txt

# TODO: Add mininet-based tests
script: make tests-travis

notifications:
  email:
    on_success: change
    on_failure: always
